# Generated by Django 6.1.1 on 2026-09-05 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='equipment/')),
            ],
            options={
                'verbose_name': 'equipamento',
                'verbose_name_plural': 'equipamentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Glassware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='glassware/')),
            ],
            options={
                'verbose_name': 'tipo de copo',
                'verbose_name_plural': 'tipos de copo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='ingredients/')),
                ('is_alcoholic', models.BooleanField(default=False, verbose_name='contém álcool')),
            ],
            options={
                'verbose_name': 'ingrediente',
                'verbose_name_plural': 'ingredientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'categoria de ingrediente',
                'verbose_name_plural': 'categorias de ingredientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField()),
                ('instructions', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'técnica',
                'verbose_name_plural': 'técnicas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField()),
                ('instructions', models.TextField(help_text='Descreva o preparo passo a passo.')),
                ('image', models.ImageField(blank=True, upload_to='cocktails/')),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Intermediário'), ('hard', 'Difícil')], default='easy', max_length=10)),
                ('preparation_time', models.PositiveSmallIntegerField(default=5, help_text='Tempo estimado em minutos.')),
                ('garnish', models.CharField(blank=True, max_length=150, verbose_name='guarnição')),
                ('is_alcoholic', models.BooleanField(default=True, verbose_name='contém álcool')),
                ('is_published', models.BooleanField(default=False, verbose_name='publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ManyToManyField(blank=True, related_name='cocktails', to='cocktails.equipment')),
                ('glassware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cocktails', to='cocktails.glassware')),
            ],
            options={
                'verbose_name': 'drink',
                'verbose_name_plural': 'drinks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CocktailIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('unit', models.CharField(choices=[('ml', 'ml'), ('oz', 'oz'), ('g', 'g'), ('unit', 'unidade'), ('dash', 'dash'), ('bar_spoon', 'colher bailarina'), ('to_taste', 'a gosto')], default='ml', max_length=20)),
                ('notes', models.CharField(blank=True, help_text='Ex.: cortado em cubos ou recém-espremido.', max_length=150)),
                ('is_optional', models.BooleanField(default=False, verbose_name='opcional')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_items', to='cocktails.cocktail')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cocktail_items', to='cocktails.ingredient')),
            ],
            options={
                'verbose_name': 'ingrediente do drink',
                'verbose_name_plural': 'ingredientes do drink',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredients',
            field=models.ManyToManyField(related_name='cocktails', through='cocktails.CocktailIngredient', to='cocktails.ingredient'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='cocktails.ingredientcategory'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='techniques',
            field=models.ManyToManyField(blank=True, related_name='cocktails', to='cocktails.technique'),
        ),
        migrations.AddConstraint(
            model_name='cocktailingredient',
            constraint=models.UniqueConstraint(fields=('cocktail', 'ingredient'), name='unique_ingredient_per_cocktail'),
        ),
    ]
