# Generated by Django 6.1.1 on 2026-09-09 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='cocktails.cocktail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocktail_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cocktail favorito',
                'verbose_name_plural': 'cocktails favoritos',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'cocktail'), name='unique_user_cocktail_favorite')],
            },
        ),
    ]
