# Generated by Django 6.1.1 on 2026-10-02 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechniqueEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, verbose_name='obrigatório')),
                ('notes', models.CharField(blank=True, help_text='Informações adicionais sobre o uso do equipamento.', max_length=150)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technique_items', to='cocktails.equipment')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='cocktails.technique')),
            ],
            options={
                'verbose_name': 'equipamento da técnica',
                'verbose_name_plural': 'equipamentos da técnica',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='technique',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='techniques', through='cocktails.TechniqueEquipment', to='cocktails.equipment'),
        ),
        migrations.AddConstraint(
            model_name='techniqueequipment',
            constraint=models.UniqueConstraint(fields=('technique', 'equipment'), name='unique_equipment_per_technique'),
        ),
    ]
