# Generated by Django 6.1.1 on 2026-09-06 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Iniciante'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado')], default='beginner', max_length=20)),
                ('reading_time', models.PositiveSmallIntegerField(default=5)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('cocktails', models.ManyToManyField(blank=True, related_name='lessons', to='cocktails.cocktail')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.learningpath')),
                ('techniques', models.ManyToManyField(blank=True, related_name='lessons', to='cocktails.technique')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
