# Generated by Django 6.1.1 on 2026-09-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='cocktails.equipment'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='cocktails.ingredient'),
        ),
    ]
